### ISSUE TITLE
Beta sympathique à ameliorer !

### ISSUE THREAD

**Issue by malexxx** [olup/lunii-admin#1]
Félicitation pour ton travail ! Le Code est assez propre et l'idée d'une alternative à studio sans java me plait beaucoup.

Dans les choses facile à améliorer :
- ajouter une barre de progression lors de l'envoi/suppression d'un pack

Dans les moins facile :
-  Ajouter les métadata dans l'interface (thumbnails, title des packs officiel et non officiel)

**Comment by olup** [comment]
Cool ! First issue 👍 Thanks a lot for sending those two proposals.

- Add a progress bar : I thought I had one! I'll definitely add a loader with some explanations on what's happening behind the curtain.

- Add metadatas : MD from lunii official packs are there (title, I don't know if thumbnails and description is useful but why not)  but for custom packs only the ones installed with this tool will be there (because this tool adds them to the lunii device itself, which STUdio doesn't). I need to figure out a way to grab the local STUdio database to add local MD to the packs on the device.

Those two: definitely on my list 😄
