### ISSUE TITLE
Feature request: Import pack from STU

### ISSUE THREAD

**Issue by charafsalmi** [olup/lunii-admin#2]
Great start! Your job is amazing. Kudos for the M1 Silicon support.

One feature that would be useful is the ability to import packs from [m12l's Studio](https://github.com/marian-m12l/studio) to convert them and import them into your clever simpler directory structure.

Hopefully, it's not a huge job.

**Comment by olup** [comment]
Sorry, I actually did not see this issue, would this feature request still be of use ? If so, I can look into it.

**Comment by olup** [comment]
Actually, you can install packs from STUdio into the Lunii with lunii-admin, so I guess you are asking for a way to then convert it in lunii-admin generated packs's structure ?

This is not always possible, because I assume a simple "tree" structure whereas STUdio packs can have virtually any structure, any links between stages (like from a child to a parent). The tool is very powerful, but I think overkill for 99% of a usual I-want-to-put-my-stuff-on-lunii kinds of use. 

By the way, lunii-admin's structure replicates the equivalent feature on the official lunii mobile app.

**Comment by olup** [comment]
And just a last precision, pack created with lunii-admin are actually in the STUdio format, and should be cross-compatible (not tested 100% tho :-) )
